---
mgmt_ip: 127.0.0.1
netconf_port: 2123
ssh_port: 2122
username: vagrant
password: vagrant
hostname: iosxe1
interfaces:
  - interface_type: GigabitEthernet
    interface_id: 2
    description: Link 2 - Configured by Ansible with Vagrant
    ip_address: 192.168.100.20
    subnet_mask: 255.255.255.0
  - interface_type: GigabitEthernet
    interface_id: 3
    description: Link 3 - Configured by Ansible with Vagrant
    ip_address: 192.168.101.20
    subnet_mask: 255.255.255.0
